// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.23.2
// source: badge.proto

package transfer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 请求红点信息
// ResponseType = BadgeInfoResp
// MessageVerb = POST
// GameUrlOpcode = api/badge/info
// RouteId = 1150
type BadgeInfoReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BadgeInfoReq) Reset() {
	*x = BadgeInfoReq{}
	mi := &file_badge_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BadgeInfoReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BadgeInfoReq) ProtoMessage() {}

func (x *BadgeInfoReq) ProtoReflect() protoreflect.Message {
	mi := &file_badge_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BadgeInfoReq.ProtoReflect.Descriptor instead.
func (*BadgeInfoReq) Descriptor() ([]byte, []int) {
	return file_badge_proto_rawDescGZIP(), []int{0}
}

type BadgeInfoResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*RedPointData        `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"` // 拥有红点的模块
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BadgeInfoResp) Reset() {
	*x = BadgeInfoResp{}
	mi := &file_badge_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BadgeInfoResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BadgeInfoResp) ProtoMessage() {}

func (x *BadgeInfoResp) ProtoReflect() protoreflect.Message {
	mi := &file_badge_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BadgeInfoResp.ProtoReflect.Descriptor instead.
func (*BadgeInfoResp) Descriptor() ([]byte, []int) {
	return file_badge_proto_rawDescGZIP(), []int{1}
}

func (x *BadgeInfoResp) GetData() []*RedPointData {
	if x != nil {
		return x.Data
	}
	return nil
}

// 请求设置红点
// ResponseType = SetBadgeResp
// MessageVerb = POST
// GameUrlOpcode = api/badge/set
// RouteId = 1151
type SetBadgeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*RedPointData        `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"` // 设置对应模块的红点
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBadgeReq) Reset() {
	*x = SetBadgeReq{}
	mi := &file_badge_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBadgeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBadgeReq) ProtoMessage() {}

func (x *SetBadgeReq) ProtoReflect() protoreflect.Message {
	mi := &file_badge_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBadgeReq.ProtoReflect.Descriptor instead.
func (*SetBadgeReq) Descriptor() ([]byte, []int) {
	return file_badge_proto_rawDescGZIP(), []int{2}
}

func (x *SetBadgeReq) GetData() []*RedPointData {
	if x != nil {
		return x.Data
	}
	return nil
}

type SetBadgeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetBadgeResp) Reset() {
	*x = SetBadgeResp{}
	mi := &file_badge_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetBadgeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetBadgeResp) ProtoMessage() {}

func (x *SetBadgeResp) ProtoReflect() protoreflect.Message {
	mi := &file_badge_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetBadgeResp.ProtoReflect.Descriptor instead.
func (*SetBadgeResp) Descriptor() ([]byte, []int) {
	return file_badge_proto_rawDescGZIP(), []int{3}
}

// 请求清除红点
// ResponseType = ClearBadgeResp
// MessageVerb = POST
// GameUrlOpcode = api/badge/clear
// RouteId = 1152
type ClearBadgeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*RedPointData        `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"` // 清除对应模块
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearBadgeReq) Reset() {
	*x = ClearBadgeReq{}
	mi := &file_badge_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearBadgeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearBadgeReq) ProtoMessage() {}

func (x *ClearBadgeReq) ProtoReflect() protoreflect.Message {
	mi := &file_badge_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearBadgeReq.ProtoReflect.Descriptor instead.
func (*ClearBadgeReq) Descriptor() ([]byte, []int) {
	return file_badge_proto_rawDescGZIP(), []int{4}
}

func (x *ClearBadgeReq) GetData() []*RedPointData {
	if x != nil {
		return x.Data
	}
	return nil
}

type ClearBadgeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClearBadgeResp) Reset() {
	*x = ClearBadgeResp{}
	mi := &file_badge_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClearBadgeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClearBadgeResp) ProtoMessage() {}

func (x *ClearBadgeResp) ProtoReflect() protoreflect.Message {
	mi := &file_badge_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClearBadgeResp.ProtoReflect.Descriptor instead.
func (*ClearBadgeResp) Descriptor() ([]byte, []int) {
	return file_badge_proto_rawDescGZIP(), []int{5}
}

// 红点信息
type RedPointData struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// 模块唯一标识
	Module int32 `protobuf:"varint,1,opt,name=module,proto3" json:"module,omitempty"`
	// 配置ID
	Cid int32 `protobuf:"varint,2,opt,name=cid,proto3" json:"cid,omitempty"`
	// 过期时间戳
	Expire        int64 `protobuf:"varint,3,opt,name=expire,proto3" json:"expire,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedPointData) Reset() {
	*x = RedPointData{}
	mi := &file_badge_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedPointData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedPointData) ProtoMessage() {}

func (x *RedPointData) ProtoReflect() protoreflect.Message {
	mi := &file_badge_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedPointData.ProtoReflect.Descriptor instead.
func (*RedPointData) Descriptor() ([]byte, []int) {
	return file_badge_proto_rawDescGZIP(), []int{6}
}

func (x *RedPointData) GetModule() int32 {
	if x != nil {
		return x.Module
	}
	return 0
}

func (x *RedPointData) GetCid() int32 {
	if x != nil {
		return x.Cid
	}
	return 0
}

func (x *RedPointData) GetExpire() int64 {
	if x != nil {
		return x.Expire
	}
	return 0
}

var File_badge_proto protoreflect.FileDescriptor

const file_badge_proto_rawDesc = "" +
	"\n" +
	"\vbadge.proto\x12\btransfer\"\x0e\n" +
	"\fBadgeInfoReq\";\n" +
	"\rBadgeInfoResp\x12*\n" +
	"\x04data\x18\x01 \x03(\v2\x16.transfer.RedPointDataR\x04data\"9\n" +
	"\vSetBadgeReq\x12*\n" +
	"\x04data\x18\x01 \x03(\v2\x16.transfer.RedPointDataR\x04data\"\x0e\n" +
	"\fSetBadgeResp\";\n" +
	"\rClearBadgeReq\x12*\n" +
	"\x04data\x18\x01 \x03(\v2\x16.transfer.RedPointDataR\x04data\"\x10\n" +
	"\x0eClearBadgeResp\"P\n" +
	"\fRedPointData\x12\x16\n" +
	"\x06module\x18\x01 \x01(\x05R\x06module\x12\x10\n" +
	"\x03cid\x18\x02 \x01(\x05R\x03cid\x12\x16\n" +
	"\x06expire\x18\x03 \x01(\x03R\x06expireBCZAgit.tencent.com/Rminigame/rmini-protocol/src/modular/api/transferb\x06proto3"

var (
	file_badge_proto_rawDescOnce sync.Once
	file_badge_proto_rawDescData []byte
)

func file_badge_proto_rawDescGZIP() []byte {
	file_badge_proto_rawDescOnce.Do(func() {
		file_badge_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_badge_proto_rawDesc), len(file_badge_proto_rawDesc)))
	})
	return file_badge_proto_rawDescData
}

var file_badge_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_badge_proto_goTypes = []any{
	(*BadgeInfoReq)(nil),   // 0: transfer.BadgeInfoReq
	(*BadgeInfoResp)(nil),  // 1: transfer.BadgeInfoResp
	(*SetBadgeReq)(nil),    // 2: transfer.SetBadgeReq
	(*SetBadgeResp)(nil),   // 3: transfer.SetBadgeResp
	(*ClearBadgeReq)(nil),  // 4: transfer.ClearBadgeReq
	(*ClearBadgeResp)(nil), // 5: transfer.ClearBadgeResp
	(*RedPointData)(nil),   // 6: transfer.RedPointData
}
var file_badge_proto_depIdxs = []int32{
	6, // 0: transfer.BadgeInfoResp.data:type_name -> transfer.RedPointData
	6, // 1: transfer.SetBadgeReq.data:type_name -> transfer.RedPointData
	6, // 2: transfer.ClearBadgeReq.data:type_name -> transfer.RedPointData
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_badge_proto_init() }
func file_badge_proto_init() {
	if File_badge_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_badge_proto_rawDesc), len(file_badge_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_badge_proto_goTypes,
		DependencyIndexes: file_badge_proto_depIdxs,
		MessageInfos:      file_badge_proto_msgTypes,
	}.Build()
	File_badge_proto = out.File
	file_badge_proto_goTypes = nil
	file_badge_proto_depIdxs = nil
}
